print("Hello World!")
print("My Name Is Suyog")
print('a = 10')
print('b = 20')
print('a + b =', 10 + 20)
print('a - b =', 10 - 20)
print('a * b =', 10 * 20)
print("\n I am learning Python from codingal \n")